name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1


    - name: Build and push Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        CONN_STR: ${{ vars.MONGODB_CONN_STRING }}
        PORT: ${{ vars.PORT }}
        SECRET: ${{ vars.JWT_SECRET }}
      run: |
        docker build \
        --build-arg CONN_STR=${{ vars.MONGODB_CONN_STRING }} \
        --build-arg PRT=${{ vars.PORT }} \
        --build-arg TOK_SCR=${{ vars.JWT_SECRET }} \
        -t kavindusanjula/project-manager-backend .
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        docker push kavindusanjula/project-manager-backend

  # update_ssh_linode:
  #   name: Telling Linode Server to Update
  #   needs: "push_to_registry"
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: executing remote ssh commands using password
  #     uses: appleboy/ssh-action@master
  #     with:
  #       host: ${{ secrets.HOST }}
  #       username: ${{ secrets.USERNAME }}
  #       password: ${{ secrets.PASSWORD }}
  #       port: ${{ secrets.PORT }}
  #       script: bash update.sh